-- VERIFICACION de migraciones 073 a 101 en produccion (SOLO LEE; no cambia nada).
-- Devuelve las columnas y tablas que DEBERIAN existir y no existen. Si no devuelve filas, esta todo aplicado.
-- La columna "migracion" dice cual archivo de supabase/migrations hay que correr.
WITH esperado(migracion, tipo, tabla, columna) AS (
  VALUES
  ('073','col','plan_limits','email_quota'),
  ('073','col','plan_limits','whatsapp_quota'),
  ('073','col','tenants','email_quota_override'),
  ('073','col','tenants','whatsapp_quota_override'),
  ('074','col','message_usage','reference_id'),
  ('077','col','tenants','onboarding_completed'),
  ('078','col','tenants','business_category'),
  ('078','col','tenants','client_files_enabled'),
  ('080','col','profiles','birth_date'),
  ('081','col','subscriptions','payment_gateway'),
  ('081','col','tenants','city'),
  ('082','col','tenants','banner_url'),
  ('082','col','tenants','booking_view_mode'),
  ('082','col','tenants','description'),
  ('082','col','tenants','google_maps_url'),
  ('082','col','tenants','google_rating'),
  ('082','col','tenants','google_reviews_count'),
  ('084','col','plan_limits','included_professionals'),
  ('084','col','signup_requests','professionals'),
  ('084','col','subscriptions','mp_preapproval_id'),
  ('085','col','signup_requests','mp_preference_id'),
  ('085','col','subscriptions','renewal_reminder_stage'),
  ('086','col','profiles','theme'),
  ('087','col','tenants','calendar_group_week'),
  ('089','col','profiles','manager_name'),
  ('090','col','transactions','accounting_month'),
  ('090','col','transactions','created_by'),
  ('090','col','transactions','fixed_category'),
  ('091','col','products','sales_commission_type'),
  ('091','col','products','sales_commission_value'),
  ('091','col','professional_settlements','daily_rate_override'),
  ('091','col','professional_settlements','days_override'),
  ('091','col','professional_settlements','worked_dates'),
  ('091','col','tenants','pro_ledger_enabled'),
  ('092','col','products','category'),
  ('092','col','products','product_type'),
  ('092','col','tenants','supply_request_email'),
  ('093','col','tenants','max_clients_per_slot'),
  ('094','col','profiles','has_labor_contract'),
  ('094','col','tenants','cash_cap'),
  ('094','col','tenants','standby_v2_enabled'),
  ('095','col','appointments','auto_assigned'),
  ('095','col','tenants','booking_reco_month'),
  ('095','col','tenants','booking_rule'),
  ('096','col','employee_files','cost_center'),
  ('096','col','employee_files','position'),
  ('096','col','employee_files','rut'),
  ('097','col','problem_reports','consent'),
  ('097','col','problem_reports','declared_cash'),
  ('097','col','problem_reports','resolution_note'),
  ('097','col','problem_reports','shown_cash'),
  ('097','col','transactions','origin'),
  ('098','col','tenants','caja_lock_enabled'),
  ('099','col','tenants','booking_window_days'),
  ('100','col','tenants','notification_center_enabled'),
  ('101','col','clients','do_not_contact'),
  ('101','col','clients','marketing_consent'),
  ('101','col','clients','marketing_consent_at'),
  ('101','col','profiles','personal_pin_hash'),
  ('073','tabla','message_usage',''),
  ('075','tabla','quota_purchase_requests',''),
  ('078','tabla','client_documents',''),
  ('081','tabla','gateway_fees',''),
  ('083','tabla','signup_requests',''),
  ('083','tabla','subscription_payments',''),
  ('090','tabla','month_closings',''),
  ('091','tabla','professional_ledger',''),
  ('091','tabla','professional_settlement_log',''),
  ('091','tabla','professional_settlements',''),
  ('092','tabla','product_categories',''),
  ('092','tabla','suppliers',''),
  ('092','tabla','supply_requests',''),
  ('094','tabla','cash_withdrawals',''),
  ('094','tabla','payroll_discounts',''),
  ('094','tabla','problem_reports',''),
  ('095','tabla','booking_rule_pros',''),
  ('095','tabla','professional_vacations',''),
  ('096','tabla','employee_files',''),
  ('096','tabla','payroll_params',''),
  ('096','tabla','payslips',''),
  ('097','tabla','cash_adjustments',''),
  ('100','tabla','notification_preferences',''),
  ('100','tabla','notifications','')
)
SELECT e.migracion, e.tipo, e.tabla, e.columna
FROM esperado e
LEFT JOIN information_schema.columns c
  ON e.tipo = 'col' AND c.table_schema = 'public' AND c.table_name = e.tabla AND c.column_name = e.columna
LEFT JOIN information_schema.tables t
  ON e.tipo = 'tabla' AND t.table_schema = 'public' AND t.table_name = e.tabla
WHERE (e.tipo = 'col' AND c.column_name IS NULL)
   OR (e.tipo = 'tabla' AND t.table_name IS NULL)
ORDER BY e.migracion, e.tabla, e.columna;
